apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullname" . }}-worker
  labels:
  {{- include "charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.config.worker_num | int }}
  selector:
    matchLabels:
      app: xinference-worker
    {{- include "charts.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.xinferenceWorker.strategy.type }}
  template:
    metadata:
      labels:
        app: xinference-worker
      {{- include "charts.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.config.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.config.imagePullSecrets | nindent 8 }}
      {{- end }}
      initContainers:
      - name: check-supervisor
        image: {{ .Values.config.curl_image | quote }}
        command: {{- toYaml .Values.xinferenceWorker.worker.initContainers.command | nindent 8 }}
      containers:
      - args: {{- toYaml .Values.xinferenceWorker.worker.args | nindent 8 }}
        command:
        - xinference-worker
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: XINFERENCE_MODEL_SRC
          value: {{ .Values.config.model_src }}
{{- if .Values.config.persistence.enabled }}
        - name: XINFERENCE_HOME
          value: {{ .Values.config.persistence.mountPath }}
{{- end }}
{{- range $key, $value := .Values.config.extra_envs }}
        - name: {{ $key }}
          value: {{ $value }}
{{- end }}
        - name: XINFERENCE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
{{- if .Values.xinferenceWorker.worker.image }}
        image: {{ .Values.xinferenceWorker.worker.image | quote }}
{{- else if .Values.config.xinference_image }}
        image: {{ .Values.config.xinference_image | quote }}
{{- else }}
        image: "xprobe/xinference:{{ .Chart.AppVersion }}"
{{- end }}
{{- if .Values.config.image_pull_policy }}
        imagePullPolicy: {{ .Values.config.image_pull_policy }}
{{- end }}
        name: worker
        ports: {{- toYaml .Values.xinferenceWorker.worker.ports | nindent 10 }}
        resources: {{- toYaml .Values.xinferenceWorker.worker.resources | nindent 10 }}
{{- if .Values.config.persistence.enabled }}
        volumeMounts:
          - mountPath: {{ .Values.config.persistence.mountPath }}
            name: xinference-home
      volumes:
        - name: xinference-home
          persistentVolumeClaim:
            claimName: xinference-shared-volume-claim
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: service-worker
  labels:
  {{- include "charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceWorker.type }}
  selector:
    app: xinference-worker
  {{- include "charts.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.serviceWorker.ports | toYaml | nindent 2 }}
